"""empty message

Revision ID: 3603abfc5821
Revises: 
Create Date: 2020-04-15 17:08:24.927659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3603abfc5821'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meditation', sa.Column('was_added_after_session', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meditation', 'was_added_after_session')
    # ### end Alembic commands ###
